/*
Player Authentication Admin API

# Introduction This is the Admin API specification for the Unity Authentication service that allows player authentication. To use this API, you must first enable it through the Unity Gaming Services dashboard.  For more information about how to set up Service Account Authentication, please read here: https://services.docs.unity.com/docs/service-account-auth  ## Rate Limits The API has rate limiting in place. Request are limited to 10 requests per second, and 500 requests per 30 minute period.  The API responds with a `429` HTTP status code if the rate limit is exceeded.  It will also respond with a `Retry-After` header to be used in conjunction with a client's retry logic. The value is the number of seconds until a request for the given player will be accepted. 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityauth

import (
	"encoding/json"
)

// checks if the PlayerAuthListProjectUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayerAuthListProjectUserResponse{}

// PlayerAuthListProjectUserResponse represents a list of players from a project.
type PlayerAuthListProjectUserResponse struct {
	// The next page token if available. Needed for the next batch GET request of players.
	Next *string `json:"next,omitempty"`
	// Resulting collection of Players.
	Results []PlayerAuthListProjectUserResponseUser `json:"results,omitempty"`
}

// NewPlayerAuthListProjectUserResponse instantiates a new PlayerAuthListProjectUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerAuthListProjectUserResponse() *PlayerAuthListProjectUserResponse {
	this := PlayerAuthListProjectUserResponse{}
	return &this
}

// NewPlayerAuthListProjectUserResponseWithDefaults instantiates a new PlayerAuthListProjectUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerAuthListProjectUserResponseWithDefaults() *PlayerAuthListProjectUserResponse {
	this := PlayerAuthListProjectUserResponse{}
	return &this
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PlayerAuthListProjectUserResponse) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerAuthListProjectUserResponse) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PlayerAuthListProjectUserResponse) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PlayerAuthListProjectUserResponse) SetNext(v string) {
	o.Next = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *PlayerAuthListProjectUserResponse) GetResults() []PlayerAuthListProjectUserResponseUser {
	if o == nil || IsNil(o.Results) {
		var ret []PlayerAuthListProjectUserResponseUser
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerAuthListProjectUserResponse) GetResultsOk() ([]PlayerAuthListProjectUserResponseUser, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *PlayerAuthListProjectUserResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []PlayerAuthListProjectUserResponseUser and assigns it to the Results field.
func (o *PlayerAuthListProjectUserResponse) SetResults(v []PlayerAuthListProjectUserResponseUser) {
	o.Results = v
}

func (o PlayerAuthListProjectUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayerAuthListProjectUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullablePlayerAuthListProjectUserResponse struct {
	value *PlayerAuthListProjectUserResponse
	isSet bool
}

func (v NullablePlayerAuthListProjectUserResponse) Get() *PlayerAuthListProjectUserResponse {
	return v.value
}

func (v *NullablePlayerAuthListProjectUserResponse) Set(val *PlayerAuthListProjectUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerAuthListProjectUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerAuthListProjectUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerAuthListProjectUserResponse(val *PlayerAuthListProjectUserResponse) *NullablePlayerAuthListProjectUserResponse {
	return &NullablePlayerAuthListProjectUserResponse{value: val, isSet: true}
}

func (v NullablePlayerAuthListProjectUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayerAuthListProjectUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


