/*
Player Authentication API

# Introduction This is the API specification for the Unity Authentication service that allows player authentication.  ## Rate Limits The API has rate limiting in place. The endpoints are limited to 15 requests per second on a per-IP basis, and 300 requests over 30 minutes. The API responds with a `429` HTTP status code if the rate limit is exceeded. It will also respond with a `Retry-After` header to be used in conjunction with a client's retry logic. The value is the number of seconds until a request for the given player will be accepted. 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityauth

import (
	"encoding/json"
)

// checks if the SignUpAnonymouslyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignUpAnonymouslyRequest{}

// SignUpAnonymouslyRequest the request body for anonymous signup
type SignUpAnonymouslyRequest struct {
	// String value used to associate a client session with an Id Token, and to mitigate replay attacks. If this field is provided, the nonce claim in response id token has a matching value.
	Nonce *string `json:"nonce,omitempty"`
}

// NewSignUpAnonymouslyRequest instantiates a new SignUpAnonymouslyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignUpAnonymouslyRequest() *SignUpAnonymouslyRequest {
	this := SignUpAnonymouslyRequest{}
	return &this
}

// NewSignUpAnonymouslyRequestWithDefaults instantiates a new SignUpAnonymouslyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignUpAnonymouslyRequestWithDefaults() *SignUpAnonymouslyRequest {
	this := SignUpAnonymouslyRequest{}
	return &this
}

// GetNonce returns the Nonce field value if set, zero value otherwise.
func (o *SignUpAnonymouslyRequest) GetNonce() string {
	if o == nil || IsNil(o.Nonce) {
		var ret string
		return ret
	}
	return *o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignUpAnonymouslyRequest) GetNonceOk() (*string, bool) {
	if o == nil || IsNil(o.Nonce) {
		return nil, false
	}
	return o.Nonce, true
}

// HasNonce returns a boolean if a field has been set.
func (o *SignUpAnonymouslyRequest) HasNonce() bool {
	if o != nil && !IsNil(o.Nonce) {
		return true
	}

	return false
}

// SetNonce gets a reference to the given string and assigns it to the Nonce field.
func (o *SignUpAnonymouslyRequest) SetNonce(v string) {
	o.Nonce = &v
}

func (o SignUpAnonymouslyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignUpAnonymouslyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nonce) {
		toSerialize["nonce"] = o.Nonce
	}
	return toSerialize, nil
}

type NullableSignUpAnonymouslyRequest struct {
	value *SignUpAnonymouslyRequest
	isSet bool
}

func (v NullableSignUpAnonymouslyRequest) Get() *SignUpAnonymouslyRequest {
	return v.value
}

func (v *NullableSignUpAnonymouslyRequest) Set(val *SignUpAnonymouslyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignUpAnonymouslyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignUpAnonymouslyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignUpAnonymouslyRequest(val *SignUpAnonymouslyRequest) *NullableSignUpAnonymouslyRequest {
	return &NullableSignUpAnonymouslyRequest{value: val, isSet: true}
}

func (v NullableSignUpAnonymouslyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignUpAnonymouslyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


