/*
Player Authentication Admin API

# Introduction This is the Admin API specification for the Unity Authentication service that allows player authentication. To use this API, you must first enable it through the Unity Gaming Services dashboard.  For more information about how to set up Service Account Authentication, please read here: https://services.docs.unity.com/docs/service-account-auth  ## Rate Limits The API has rate limiting in place. Request are limited to 10 requests per second, and 500 requests per 30 minute period.  The API responds with a `429` HTTP status code if the rate limit is exceeded.  It will also respond with a `Retry-After` header to be used in conjunction with a client's retry logic. The value is the number of seconds until a request for the given player will be accepted. 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityauth

import (
	"encoding/json"
)

// checks if the PlayerAuthPlayerProjectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayerAuthPlayerProjectResponse{}

// PlayerAuthPlayerProjectResponse represents a player provided by an External Provider
type PlayerAuthPlayerProjectResponse struct {
	// Whether the player is enabled or disabled by admin.
	Disabled *bool `json:"disabled,omitempty"`
	// This is the response returned when get player is called.
	ExternalIds []PlayerAuthExternalId `json:"externalIds,omitempty"`
	// The player Id. The Id is unique within the Id domain.
	Id *string `json:"id,omitempty"`
	// When the player was created at. It is a unix timestamp.
	CreatedAt *string `json:"createdAt,omitempty"`
	// When the player last logged in. It is a unix timestamp.
	LastLoginAt *string `json:"lastLoginAt,omitempty"`
}

// NewPlayerAuthPlayerProjectResponse instantiates a new PlayerAuthPlayerProjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerAuthPlayerProjectResponse() *PlayerAuthPlayerProjectResponse {
	this := PlayerAuthPlayerProjectResponse{}
	return &this
}

// NewPlayerAuthPlayerProjectResponseWithDefaults instantiates a new PlayerAuthPlayerProjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerAuthPlayerProjectResponseWithDefaults() *PlayerAuthPlayerProjectResponse {
	this := PlayerAuthPlayerProjectResponse{}
	return &this
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *PlayerAuthPlayerProjectResponse) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerAuthPlayerProjectResponse) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *PlayerAuthPlayerProjectResponse) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *PlayerAuthPlayerProjectResponse) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetExternalIds returns the ExternalIds field value if set, zero value otherwise.
func (o *PlayerAuthPlayerProjectResponse) GetExternalIds() []PlayerAuthExternalId {
	if o == nil || IsNil(o.ExternalIds) {
		var ret []PlayerAuthExternalId
		return ret
	}
	return o.ExternalIds
}

// GetExternalIdsOk returns a tuple with the ExternalIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerAuthPlayerProjectResponse) GetExternalIdsOk() ([]PlayerAuthExternalId, bool) {
	if o == nil || IsNil(o.ExternalIds) {
		return nil, false
	}
	return o.ExternalIds, true
}

// HasExternalIds returns a boolean if a field has been set.
func (o *PlayerAuthPlayerProjectResponse) HasExternalIds() bool {
	if o != nil && !IsNil(o.ExternalIds) {
		return true
	}

	return false
}

// SetExternalIds gets a reference to the given []PlayerAuthExternalId and assigns it to the ExternalIds field.
func (o *PlayerAuthPlayerProjectResponse) SetExternalIds(v []PlayerAuthExternalId) {
	o.ExternalIds = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlayerAuthPlayerProjectResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerAuthPlayerProjectResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlayerAuthPlayerProjectResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlayerAuthPlayerProjectResponse) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PlayerAuthPlayerProjectResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerAuthPlayerProjectResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PlayerAuthPlayerProjectResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *PlayerAuthPlayerProjectResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetLastLoginAt returns the LastLoginAt field value if set, zero value otherwise.
func (o *PlayerAuthPlayerProjectResponse) GetLastLoginAt() string {
	if o == nil || IsNil(o.LastLoginAt) {
		var ret string
		return ret
	}
	return *o.LastLoginAt
}

// GetLastLoginAtOk returns a tuple with the LastLoginAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerAuthPlayerProjectResponse) GetLastLoginAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastLoginAt) {
		return nil, false
	}
	return o.LastLoginAt, true
}

// HasLastLoginAt returns a boolean if a field has been set.
func (o *PlayerAuthPlayerProjectResponse) HasLastLoginAt() bool {
	if o != nil && !IsNil(o.LastLoginAt) {
		return true
	}

	return false
}

// SetLastLoginAt gets a reference to the given string and assigns it to the LastLoginAt field.
func (o *PlayerAuthPlayerProjectResponse) SetLastLoginAt(v string) {
	o.LastLoginAt = &v
}

func (o PlayerAuthPlayerProjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayerAuthPlayerProjectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.ExternalIds) {
		toSerialize["externalIds"] = o.ExternalIds
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.LastLoginAt) {
		toSerialize["lastLoginAt"] = o.LastLoginAt
	}
	return toSerialize, nil
}

type NullablePlayerAuthPlayerProjectResponse struct {
	value *PlayerAuthPlayerProjectResponse
	isSet bool
}

func (v NullablePlayerAuthPlayerProjectResponse) Get() *PlayerAuthPlayerProjectResponse {
	return v.value
}

func (v *NullablePlayerAuthPlayerProjectResponse) Set(val *PlayerAuthPlayerProjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerAuthPlayerProjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerAuthPlayerProjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerAuthPlayerProjectResponse(val *PlayerAuthPlayerProjectResponse) *NullablePlayerAuthPlayerProjectResponse {
	return &NullablePlayerAuthPlayerProjectResponse{value: val, isSet: true}
}

func (v NullablePlayerAuthPlayerProjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayerAuthPlayerProjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


