/*
Player Authentication API

# Introduction This is the API specification for the Unity Authentication service that allows player authentication.  ## Rate Limits The API has rate limiting in place. The endpoints are limited to 15 requests per second on a per-IP basis, and 300 requests over 30 minutes. The API responds with a `429` HTTP status code if the rate limit is exceeded. It will also respond with a `Retry-After` header to be used in conjunction with a client's retry logic. The value is the number of seconds until a request for the given player will be accepted. 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityauth

import (
	"encoding/json"
)

// checks if the SignInWithExternalTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignInWithExternalTokenRequest{}

// SignInWithExternalTokenRequest the request body for external token authentication
type SignInWithExternalTokenRequest struct {
	// String value used to associate a client session with an Id token, and to mitigate replay attacks. If this field is provided, the nonce claim in response Id token will have a matching value.
	Nonce *string `json:"nonce,omitempty"`
	// Whether the API should only attempt to sign-in and do not create a new player if the player does not exist.
	SignInOnly *bool `json:"signInOnly,omitempty"`
	// External token that can be verified to represent a player from the id provider. This may be an id token or an access token.
	Token *string `json:"token,omitempty"`
	OculusConfig *OculusConfig `json:"oculusConfig,omitempty"`
	AppleGameCenterConfig *AppleGameCenterConfig `json:"appleGameCenterConfig,omitempty"`
	SteamConfig *SteamConfig `json:"steamConfig,omitempty"`
}

// NewSignInWithExternalTokenRequest instantiates a new SignInWithExternalTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignInWithExternalTokenRequest() *SignInWithExternalTokenRequest {
	this := SignInWithExternalTokenRequest{}
	return &this
}

// NewSignInWithExternalTokenRequestWithDefaults instantiates a new SignInWithExternalTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignInWithExternalTokenRequestWithDefaults() *SignInWithExternalTokenRequest {
	this := SignInWithExternalTokenRequest{}
	return &this
}

// GetNonce returns the Nonce field value if set, zero value otherwise.
func (o *SignInWithExternalTokenRequest) GetNonce() string {
	if o == nil || IsNil(o.Nonce) {
		var ret string
		return ret
	}
	return *o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInWithExternalTokenRequest) GetNonceOk() (*string, bool) {
	if o == nil || IsNil(o.Nonce) {
		return nil, false
	}
	return o.Nonce, true
}

// HasNonce returns a boolean if a field has been set.
func (o *SignInWithExternalTokenRequest) HasNonce() bool {
	if o != nil && !IsNil(o.Nonce) {
		return true
	}

	return false
}

// SetNonce gets a reference to the given string and assigns it to the Nonce field.
func (o *SignInWithExternalTokenRequest) SetNonce(v string) {
	o.Nonce = &v
}

// GetSignInOnly returns the SignInOnly field value if set, zero value otherwise.
func (o *SignInWithExternalTokenRequest) GetSignInOnly() bool {
	if o == nil || IsNil(o.SignInOnly) {
		var ret bool
		return ret
	}
	return *o.SignInOnly
}

// GetSignInOnlyOk returns a tuple with the SignInOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInWithExternalTokenRequest) GetSignInOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.SignInOnly) {
		return nil, false
	}
	return o.SignInOnly, true
}

// HasSignInOnly returns a boolean if a field has been set.
func (o *SignInWithExternalTokenRequest) HasSignInOnly() bool {
	if o != nil && !IsNil(o.SignInOnly) {
		return true
	}

	return false
}

// SetSignInOnly gets a reference to the given bool and assigns it to the SignInOnly field.
func (o *SignInWithExternalTokenRequest) SetSignInOnly(v bool) {
	o.SignInOnly = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *SignInWithExternalTokenRequest) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInWithExternalTokenRequest) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *SignInWithExternalTokenRequest) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *SignInWithExternalTokenRequest) SetToken(v string) {
	o.Token = &v
}

// GetOculusConfig returns the OculusConfig field value if set, zero value otherwise.
func (o *SignInWithExternalTokenRequest) GetOculusConfig() OculusConfig {
	if o == nil || IsNil(o.OculusConfig) {
		var ret OculusConfig
		return ret
	}
	return *o.OculusConfig
}

// GetOculusConfigOk returns a tuple with the OculusConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInWithExternalTokenRequest) GetOculusConfigOk() (*OculusConfig, bool) {
	if o == nil || IsNil(o.OculusConfig) {
		return nil, false
	}
	return o.OculusConfig, true
}

// HasOculusConfig returns a boolean if a field has been set.
func (o *SignInWithExternalTokenRequest) HasOculusConfig() bool {
	if o != nil && !IsNil(o.OculusConfig) {
		return true
	}

	return false
}

// SetOculusConfig gets a reference to the given OculusConfig and assigns it to the OculusConfig field.
func (o *SignInWithExternalTokenRequest) SetOculusConfig(v OculusConfig) {
	o.OculusConfig = &v
}

// GetAppleGameCenterConfig returns the AppleGameCenterConfig field value if set, zero value otherwise.
func (o *SignInWithExternalTokenRequest) GetAppleGameCenterConfig() AppleGameCenterConfig {
	if o == nil || IsNil(o.AppleGameCenterConfig) {
		var ret AppleGameCenterConfig
		return ret
	}
	return *o.AppleGameCenterConfig
}

// GetAppleGameCenterConfigOk returns a tuple with the AppleGameCenterConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInWithExternalTokenRequest) GetAppleGameCenterConfigOk() (*AppleGameCenterConfig, bool) {
	if o == nil || IsNil(o.AppleGameCenterConfig) {
		return nil, false
	}
	return o.AppleGameCenterConfig, true
}

// HasAppleGameCenterConfig returns a boolean if a field has been set.
func (o *SignInWithExternalTokenRequest) HasAppleGameCenterConfig() bool {
	if o != nil && !IsNil(o.AppleGameCenterConfig) {
		return true
	}

	return false
}

// SetAppleGameCenterConfig gets a reference to the given AppleGameCenterConfig and assigns it to the AppleGameCenterConfig field.
func (o *SignInWithExternalTokenRequest) SetAppleGameCenterConfig(v AppleGameCenterConfig) {
	o.AppleGameCenterConfig = &v
}

// GetSteamConfig returns the SteamConfig field value if set, zero value otherwise.
func (o *SignInWithExternalTokenRequest) GetSteamConfig() SteamConfig {
	if o == nil || IsNil(o.SteamConfig) {
		var ret SteamConfig
		return ret
	}
	return *o.SteamConfig
}

// GetSteamConfigOk returns a tuple with the SteamConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInWithExternalTokenRequest) GetSteamConfigOk() (*SteamConfig, bool) {
	if o == nil || IsNil(o.SteamConfig) {
		return nil, false
	}
	return o.SteamConfig, true
}

// HasSteamConfig returns a boolean if a field has been set.
func (o *SignInWithExternalTokenRequest) HasSteamConfig() bool {
	if o != nil && !IsNil(o.SteamConfig) {
		return true
	}

	return false
}

// SetSteamConfig gets a reference to the given SteamConfig and assigns it to the SteamConfig field.
func (o *SignInWithExternalTokenRequest) SetSteamConfig(v SteamConfig) {
	o.SteamConfig = &v
}

func (o SignInWithExternalTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignInWithExternalTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nonce) {
		toSerialize["nonce"] = o.Nonce
	}
	if !IsNil(o.SignInOnly) {
		toSerialize["signInOnly"] = o.SignInOnly
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.OculusConfig) {
		toSerialize["oculusConfig"] = o.OculusConfig
	}
	if !IsNil(o.AppleGameCenterConfig) {
		toSerialize["appleGameCenterConfig"] = o.AppleGameCenterConfig
	}
	if !IsNil(o.SteamConfig) {
		toSerialize["steamConfig"] = o.SteamConfig
	}
	return toSerialize, nil
}

type NullableSignInWithExternalTokenRequest struct {
	value *SignInWithExternalTokenRequest
	isSet bool
}

func (v NullableSignInWithExternalTokenRequest) Get() *SignInWithExternalTokenRequest {
	return v.value
}

func (v *NullableSignInWithExternalTokenRequest) Set(val *SignInWithExternalTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignInWithExternalTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignInWithExternalTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignInWithExternalTokenRequest(val *SignInWithExternalTokenRequest) *NullableSignInWithExternalTokenRequest {
	return &NullableSignInWithExternalTokenRequest{value: val, isSet: true}
}

func (v NullableSignInWithExternalTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignInWithExternalTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


