/*
Player Authentication API

# Introduction This is the API specification for the Unity Authentication service that allows player authentication.  ## Rate Limits The API has rate limiting in place. The endpoints are limited to 15 requests per second on a per-IP basis, and 300 requests over 30 minutes. The API responds with a `429` HTTP status code if the rate limit is exceeded. It will also respond with a `Retry-After` header to be used in conjunction with a client's retry logic. The value is the number of seconds until a request for the given player will be accepted. 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityauth

import (
	"encoding/json"
)

// checks if the CodeLinkInfoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeLinkInfoRequest{}

// CodeLinkInfoRequest Request information for a sign in code.
type CodeLinkInfoRequest struct {
	// The code from which to get the info.
	SignInCode *string `json:"signInCode,omitempty"`
}

// NewCodeLinkInfoRequest instantiates a new CodeLinkInfoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeLinkInfoRequest() *CodeLinkInfoRequest {
	this := CodeLinkInfoRequest{}
	return &this
}

// NewCodeLinkInfoRequestWithDefaults instantiates a new CodeLinkInfoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeLinkInfoRequestWithDefaults() *CodeLinkInfoRequest {
	this := CodeLinkInfoRequest{}
	return &this
}

// GetSignInCode returns the SignInCode field value if set, zero value otherwise.
func (o *CodeLinkInfoRequest) GetSignInCode() string {
	if o == nil || IsNil(o.SignInCode) {
		var ret string
		return ret
	}
	return *o.SignInCode
}

// GetSignInCodeOk returns a tuple with the SignInCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodeLinkInfoRequest) GetSignInCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SignInCode) {
		return nil, false
	}
	return o.SignInCode, true
}

// HasSignInCode returns a boolean if a field has been set.
func (o *CodeLinkInfoRequest) HasSignInCode() bool {
	if o != nil && !IsNil(o.SignInCode) {
		return true
	}

	return false
}

// SetSignInCode gets a reference to the given string and assigns it to the SignInCode field.
func (o *CodeLinkInfoRequest) SetSignInCode(v string) {
	o.SignInCode = &v
}

func (o CodeLinkInfoRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeLinkInfoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SignInCode) {
		toSerialize["signInCode"] = o.SignInCode
	}
	return toSerialize, nil
}

type NullableCodeLinkInfoRequest struct {
	value *CodeLinkInfoRequest
	isSet bool
}

func (v NullableCodeLinkInfoRequest) Get() *CodeLinkInfoRequest {
	return v.value
}

func (v *NullableCodeLinkInfoRequest) Set(val *CodeLinkInfoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeLinkInfoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeLinkInfoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeLinkInfoRequest(val *CodeLinkInfoRequest) *NullableCodeLinkInfoRequest {
	return &NullableCodeLinkInfoRequest{value: val, isSet: true}
}

func (v NullableCodeLinkInfoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeLinkInfoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


